fix customEvents channel perms overwrites
Dragory/ZeppelinBot pull request #253
Opened 2021-08-21 14:43 UTC by metal0

2021-08-21 15:02 UTC, almeidx requested changes

2021-08-21 15:02 UTC, almeidx commented on backend/src/plugins/CustomEvents/actions/setChannelPermissionOverrides.ts
> +    const perms = {};
```suggestion
    const perms: Record<PermissionString, boolean> = {};
```

2021-08-21 16:28 UTC, almeidx approved these changes

2021-09-04 16:13 UTC, merged

2021-09-04 16:13 UTC, Dragory commented
Thank you for the fix!