Custom Events fixes
Dragory/ZeppelinBot pull request #255
Opened 2021-08-21 15:00 UTC by metal0

Fixes custom events unsafe values crashing the bot and adds a sanitization check to addRoleAction for existing roles

2021-08-21 16:29 UTC, almeidx requested changes

2021-08-21 17:45 UTC, almeidx requested changes

2021-08-21 17:45 UTC, almeidx commented on backend/src/plugins/CustomEvents/actions/addRoleAction.ts
> +  const rolesToAdd = (Array.isArray(action.role) ? action.role : [action.role]).filter(id => !targetRoles.includes(id));
```suggestion
  const rolesToAdd = (Array.isArray(action.role) ? action.role : [action.role]).filter(id => !target.roles.cache.has(id));
```

2021-08-21 18:00 UTC, almeidx approved these changes

2021-09-04 16:11 UTC, merged

2021-09-04 16:11 UTC, Dragory commented
Thank you for the fix!